# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 08:46
from __future__ import unicode_literals

from django.db import migrations


def create_init_groups(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    exist_group_names = group.objects.values_list('name', flat=True)
    group_names = [
        'Doctor', 'Nurse', 'Caregiver', 'Physiotherapist', 'Psychologist', 'Social Worker', 'Administrative staff'
    ]

    group.objects.bulk_create([group(name=name) for name in group_names if name not in exist_group_names])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181025_1456'),
    ]

    operations = [
        migrations.RunPython(create_init_groups, reverse_code=migrations.RunPython.noop),
    ]
