# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_createsuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inami',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='INAMI number (accredited number for healthcare professional) '),
        ),
        migrations.AddField(
            model_name='user',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direct line'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile'),
        ),
    ]
