# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20181005_0919'),
        ('accounts', '0004_auto_20181005_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.AddField(
            model_name='user',
            name='units',
            field=models.ManyToManyField(to='units.Unit'),
        ),
    ]
