# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-05 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181008_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Hollandsk')], default='en', max_length=16, verbose_name='User langauge'),
        ),
    ]
