# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_language'),
    ]

    operations = []
