# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_additionalpermission'),
    ]

    operations = []
