# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_additionalpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user', models.CharField(max_length=255, verbose_name='Username')),
                ('email', models.CharField(max_length=255, verbose_name='User email')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient file id')),
                ('patient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient name')),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Patient id')),
                ('activity', models.TextField(blank=True, null=True)),
                ('data', models.TextField(null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'User activity',
                'verbose_name_plural': 'Users activities',
                'db_table': 'user_activities',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Hollandsk')], default='en', max_length=16, verbose_name='User language'),
        ),
    ]
