# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('accounts', '0009_auto_20190527_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=16, verbose_name='Patient id')),
                ('log_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.LogEntry', verbose_name='LogEntry')),
            ],
            options={
                'verbose_name': 'Admin User activity',
                'verbose_name_plural': 'Admin Users activities',
                'db_table': 'admin_activities',
            },
        ),
    ]
