# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Documents Types',
                'db_table': 'document_type',
                'ordering': ('name',),
            },
        ),
    ]
