# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-11 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import lifeline.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview_pdf_file',
            field=models.FileField(blank=True, null=True, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
