# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_preview_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, max_length=64, verbose_name='documents extension'),
        ),
    ]
