# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-24 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='preview_pdf_file',
        ),
    ]
