# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 07:35
from __future__ import unicode_literals

import apps.diagnostics.validators
from django.db import migrations, models
import django_extensions.db.fields
import lifeline.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(max_length=100, verbose_name='Concept ID')),
                ('term', models.CharField(max_length=255, verbose_name='Name')),
                ('term_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('term_fr', models.CharField(max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Diagnose',
                'verbose_name_plural': 'Diagnoses',
                'db_table': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='', validators=[apps.diagnostics.validators.file_extension_validator], verbose_name='Uploaded file')),
                ('label', models.CharField(choices=[('D', 'Diagnose'), ('HS', 'Health Screening')], max_length=10, verbose_name='File type')),
            ],
            options={
                'verbose_name': 'Diagnostic File',
                'verbose_name_plural': 'Diagnostic Files',
                'db_table': 'diagnostic_files',
            },
        ),
        migrations.CreateModel(
            name='HealthScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Particular monitoring type')),
                ('type_en', models.CharField(max_length=100, null=True, verbose_name='Particular monitoring type')),
                ('type_fr', models.CharField(max_length=100, null=True, verbose_name='Particular monitoring type')),
            ],
            options={
                'verbose_name': 'Health Screening',
                'verbose_name_plural': 'Health Screenings',
                'db_table': 'health_screening',
            },
        ),
    ]
