# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 13:41
from __future__ import unicode_literals

from django.db import migrations


def add_file_placeholders(apps, schema_editor):
    DiagnosticFile = apps.get_model('diagnostics', 'DiagnosticFile')
    DiagnosticFile.objects.bulk_create((DiagnosticFile(label='diagnose'), DiagnosticFile(label='screening')))


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_file_placeholders, reverse_code=migrations.RunPython.noop),
    ]
