# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_file_placeholder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthscreening',
            old_name='type',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='healthscreening',
            old_name='type_en',
            new_name='term_en',
        ),
        migrations.RenameField(
            model_name='healthscreening',
            old_name='type_fr',
            new_name='term_fr',
        ),
    ]
