# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_auto_20181102_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Diagnostic name')),
                ('creator', models.CharField(max_length=255, verbose_name='Particular monitoring type')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('diagnose', 'Diagnose'), ('screening', 'Health Screening'), ('anamnesis', 'Medical Anamnesis and Allergies')], max_length=10, verbose_name='Type')),
                ('is_allergy', models.BooleanField(default=False, verbose_name='Is allergy')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
                'db_table': 'diagnostics',
            },
        ),
        migrations.AlterField(
            model_name='diagnosticfile',
            name='label',
            field=models.CharField(choices=[('diagnose', 'Diagnose'), ('screening', 'Health Screening'), ('anamnesis', 'Medical Anamnesis and Allergies')], max_length=10, verbose_name='File type'),
        ),
    ]
