# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20181030_0802'),
        ('diagnostics', '0004_auto_20181102_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='File'),
        ),
    ]
