# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_diagnostic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticfile',
            name='label',
            field=models.CharField(choices=[('diagnose', 'Diagnose'), ('screening', 'Health Screening'), ('anamnesis', 'Medical Anamnesis and Allergies')], max_length=12, verbose_name='File type'),
        ),
    ]
