# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_auto_20181102_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'ordering': ('-created',), 'verbose_name': 'Diagnostic', 'verbose_name_plural': 'Diagnostics'},
        ),
    ]
