# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_auto_20181105_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
