# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_auto_20181108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='term_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='healthscreening',
            name='term_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Particular monitoring type'),
        ),
    ]
