# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0009_auto_20181206_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticfile',
            name='errors',
            field=models.TextField(null=True, verbose_name='Errors from last parsing'),
        ),
        migrations.AddField(
            model_name='diagnosticfile',
            name='is_uploaded',
            field=models.BooleanField(default=False, verbose_name='File was parsed successfully'),
        ),
    ]
