# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostics', '0010_auto_20181207_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='creator',
            field=models.CharField(max_length=255, verbose_name='Creator'),
        ),
    ]
