# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0011_auto_20181210_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='diagnose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Diagnose', verbose_name='Diagnose'),
        ),
    ]
