# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0012_diagnostic_diagnose'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='screening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.HealthScreening', verbose_name='Health Screening'),
        )
    ]
