# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0014_move_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='name',
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.Diagnose', verbose_name='Diagnose'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='screening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.HealthScreening', verbose_name='Health Screening'),
        ),
    ]
