# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20181005_0919'),
        ('patients', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PR', 'Present'), ('TEMP', 'Temporary released'), ('REL', 'Released')], default='PR', max_length=7, verbose_name='Status'),
        ),
    ]
