# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20181009_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True, verbose_name='E-mail Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, choices=[('ADV', 'Adventist'), ('AOG', 'Assembly of God'), ('BAP', 'Baptist'), ('BUD', 'Buddhist'), ('CAT', 'Catholic'), ('JW', "Jehovan's Witness"), ('JSH', 'Jewish'), ('LUT', 'Lutheran'), ('MRN', 'Mormon'), ('NO', 'None'), ('ORT', 'Orthodox'), ('OTH', 'Other'), ('PST', 'Protestant'), ('QUA', 'Quaker'), ('ISL', 'Islam')], max_length=7, null=True, verbose_name='Religion'),
        ),
    ]
