# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20181030_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='file',
            name='closed_since',
            field=models.DateField(blank=True, null=True, verbose_name='Closed since'),
        ),
        migrations.AddField(
            model_name='file',
            name='temporary_released_end',
            field=models.DateField(blank=True, null=True, verbose_name='Temporary released until'),
        ),
        migrations.AddField(
            model_name='file',
            name='temporary_released_start',
            field=models.DateField(blank=True, null=True, verbose_name='Temporary released from'),
        ),
    ]
