# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20181106_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created_by')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Archive Comment',
                'verbose_name_plural': 'Archive Comments',
                'db_table': 'archive_comment',
                'ordering': ('-created',),
            },
        ),
    ]
