# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_emergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, choices=[('wife', 'Wife / Husband'), ('partner', 'Partner'), ('child', 'Child'), ('parent', 'Parent'), ('grandparent', 'Grandparent'), ('brother', 'Brother / Sister'), ('other', 'Other family member'), ('friend', 'Friend'), ('roommate', 'Roommate'), ('general', 'General practitioner'), ('specialist', 'Specialist doctor'), ('lawyer', 'Lawyer'), ('attorney', 'Attorney for financial power'), ('probation', 'Probation officer'), ('judge', 'Youth Judge'), ('educator', 'Educator'), ('other', 'Other relation')], max_length=16, null=True, verbose_name='Relation'),
        ),
        migrations.AlterField(
            model_name='file',
            name='temporary_released_end',
            field=models.DateField(blank=True, null=True, verbose_name='Released until'),
        ),
        migrations.AlterField(
            model_name='file',
            name='temporary_released_start',
            field=models.DateField(blank=True, null=True, verbose_name='Released from'),
        ),
    ]
