# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 08:54
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20181128_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ('-created',), 'verbose_name': 'Emergency Contact', 'verbose_name_plural': 'Emergency Contacts'},
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
