# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20181129_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='trusted',
            field=models.BooleanField(default=False, verbose_name='Is trusted'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone'),
        ),
    ]
