# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0016_auto_20181129_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivecomment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='archivecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
