# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20181218_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bed',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Assigned Patient's Bed"),
        )
    ]
