# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20190424_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted Contact'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for deletion'),
        ),
    ]
