# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models


def fill_up_task_count(apps, schema_editor):
    from apps.patients.tasks import invalidate_patient_task_count
    File = apps.get_model('patients', 'File')
    for file in File.objects.all():
        invalidate_patient_task_count(file.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_auto_20190603_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='due_tasks',
            field=models.IntegerField(default=0, verbose_name='Due tasks'),
        ),
        migrations.AddField(
            model_name='file',
            name='open_tasks',
            field=models.IntegerField(default=0, verbose_name='Open tasks'),
        ),
        migrations.RunPython(fill_up_task_count, reverse_code=migrations.RunPython.noop),
    ]
