# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_auto_20190612_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_gdpr_agreed',
            field=models.BooleanField(default=True, verbose_name='Consent to proceed patient data'),
        ),
    ]
