# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-19 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_patient_is_gdpr_agreed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-created',), 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
