# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-14 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import lifeline.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0018_auto_20181218_0746'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Report Logo',
                'verbose_name_plural': 'Report Logos',
                'db_table': 'logos',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('report', models.FileField(max_length=255, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='reports/', verbose_name='Report')),
                ('type', models.CharField(choices=[('medical', 'Medical Report'), ('social', 'Social Report'), ('drugs', 'List of drugs'), ('evaluation', 'Evaluation Report')], max_length=10)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ('-created',),
            },
        ),
    ]
