# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import lifeline.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_en',
            field=models.FileField(max_length=255, null=True, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='reports/', verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_fr',
            field=models.FileField(max_length=255, null=True, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='reports/', verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_nl',
            field=models.FileField(max_length=255, null=True, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='reports/', verbose_name='Report'),
        ),
    ]
