# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20181012_0945'),
        ('wounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wound',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='Patient File'),
        ),
    ]
