# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounds', '0004_auto_20181023_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolution',
            options={'ordering': ('-created',), 'verbose_name': 'Evolution', 'verbose_name_plural': 'Evolutions'},
        ),
        migrations.AddField(
            model_name='wound',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
