# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounds', '0005_auto_20181024_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='wound',
            name='treatment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wound',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
