# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import lifeline.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('wounds', '0008_auto_20181029_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='photo',
            field=models.ImageField(max_length=255, null=True, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Wound photo'),
        ),
    ]
