# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wounds', '0011_auto_20181210_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wound',
            name='treatment',
        ),
    ]
