# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 14:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import lifeline.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('message_from', models.CharField(max_length=255, verbose_name='Message From')),
                ('message_to', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Message To')),
                ('subject', models.CharField(db_index=True, max_length=255, verbose_name='Subject')),
                ('msg_content', models.TextField(db_index=True)),
                ('read_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=[], null=True, size=None)),
                ('receivers', models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL, verbose_name='Receivers')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=lifeline.storage_backends.PrivateMediaStorage(), upload_to='', verbose_name='Uploaded file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_file', to='_messages.Message', verbose_name='Message File')),
            ],
            options={
                'verbose_name': 'Message File',
                'verbose_name_plural': 'Messages Files',
                'db_table': 'message_files',
            },
        ),
    ]
