# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 12:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20181112_1338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_messages', '0002_auto_20181001_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subject', models.CharField(db_index=True, max_length=255, verbose_name='Subject')),
                ('msg_content', models.TextField()),
                ('read_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=[], null=True, size=None)),
                ('hidden_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, default=[], null=True, size=None)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='Patient File')),
            ],
            options={
                'verbose_name': 'About Patients Message',
                'verbose_name_plural': 'About Patients Messages',
                'db_table': 'about_patients_messages',
                'ordering': ('-created',),
            },
        ),
    ]
