# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0008_auto_20181012_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Medication Category',
                'verbose_name_plural': 'Medication Categories',
                'db_table': 'medication_categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('editor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Editor')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('quantity', models.CharField(max_length=255, verbose_name='Quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Category', verbose_name='Category')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescriptions',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Prescription Date')),
                ('time', models.TimeField(null=True, verbose_name='Prescription Time')),
                ('status', models.CharField(blank=True, choices=[('DONE', 'Done'), ('DISP', 'Displaced'), ('UNDN', 'Undone'), ('STOP', 'Stop'), ('SUSP', 'Suspend')], max_length=4, null=True, verbose_name='Prescription Status')),
                ('periodic', models.CharField(blank=True, choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=5, null=True, verbose_name='Prescription periodic')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('slot', models.BooleanField(default=False, verbose_name='Is time slot')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Prescription', verbose_name='Prescription')),
            ],
            options={
                'verbose_name': 'Prescription Schedule',
                'verbose_name_plural': 'Prescription Schedules',
                'db_table': 'prescription_schedules',
                'ordering': ('created',),
            },
        ),
    ]
