# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionschedule',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='PrescriptionSchedule',
        ),
    ]
