# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20181031_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('editor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Editor')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Actions')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Prescription', verbose_name='Prescription')),
            ],
            options={
                'verbose_name': 'Prescription Log',
                'verbose_name_plural': 'Prescription Logs',
                'db_table': 'prescription_logs',
                'ordering': ('-created',),
            },
        ),
    ]
