# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_auto_20190311_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=128, null=True, verbose_name='Dosage'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='unit',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='dosage',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Unit'),
        ),
    ]
