# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


def clear_medications(apps, schema_editor):
    category_model = apps.get_model('medications', 'Category')
    category_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0014_auto_20190426_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unit_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='unit_nl',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.RunPython(clear_medications, reverse_code=migrations.RunPython.noop),
    ]
