# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0015_auto_20190508_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='MedicationCategory',
        ),
    ]
