# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0017_medicationhistory_medicationtherapy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('start_of_timeslot', models.DateTimeField(verbose_name='Start of time slot')),
                ('end_of_timeslot', models.DateTimeField(verbose_name='End of time slot')),
                ('action_type', models.CharField(choices=[('default', 'Not have action'), ('D', 'Done'), ('DC', 'Done + comment'), ('DC', 'Not done')], default='default', max_length=100)),
                ('stock_type', models.CharField(choices=[('patient', 'Patient stock type')], default='patient', max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Prescription', verbose_name='Prescription')),
            ],
            options={
                'verbose_name': 'Medication intake',
                'verbose_name_plural': 'Medication intakes',
                'db_table': 'medication_intakes',
                'ordering': ('-created',),
            },
        ),
    ]
