# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0020_auto_20190909_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationcategory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='medicationcategory',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='medicationcategory',
            name='unit_en',
        ),
        migrations.RemoveField(
            model_name='medicationcategory',
            name='unit_fr',
        ),
        migrations.RemoveField(
            model_name='medicationcategory',
            name='unit_nl',
        ),
        migrations.RemoveField(
            model_name='medicationcategory',
            name='vmp_code',
        ),
        migrations.AddField(
            model_name='drug',
            name='code',
            field=models.CharField(default='code', max_length=64, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit',
            field=models.CharField(default='tab', max_length=128, verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_nl',
            field=models.CharField(max_length=128, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='drug',
            name='vmp_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='VMP Code'),
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='cycle',
            field=models.BooleanField(default=False, verbose_name='Cycle'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cycle_every_reccurence',
            field=models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=6, verbose_name='Reccurence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='cycle_every_value',
            field=models.IntegerField(default=1, verbose_name='Every'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='cycle_over_reccurence',
            field=models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=6, verbose_name='Reccurence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='cycle_over_value',
            field=models.IntegerField(default=1, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(choices=[('INDEF', 'Indefinite'), ('FIXED', 'Fixed')], default='INDEF', max_length=5, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='meal',
            field=models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='BEFORE', max_length=6, verbose_name='Meal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='mode',
            field=models.CharField(choices=[('DAYLI', 'Daily'), ('CONDITIONAL', 'Conditional')], default='DAYLI', max_length=11, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Repeat'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='repeat_every',
            field=models.IntegerField(default=1, verbose_name='Every'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='repeat_reccurence',
            field=models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=6, verbose_name='Reccurence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='action_type',
            field=models.CharField(choices=[('D', 'Done'), ('DC', 'Done + comment'), ('DC', 'Not done')], max_length=100),
        ),
    ]
