# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0023_auto_20190910_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('time-slots', 'Time slots'), ('fixed-times', 'Fixed times'), ('fixed-times-dow', 'Fixed times by day of week'), ('one-shot', 'One shot'), ('conditional', 'Conditional')], default='conditional', max_length=11),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='mode',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('CONDITIONAL', 'Conditional')], max_length=11, null=True, verbose_name='type'),
        ),
    ]
