# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0024_auto_20191002_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True, verbose_name='Day of week')),
                ('time_slot_type', models.CharField(choices=[('step', 'Step'), ('step-dow', 'Step with day of week'), ('one-shot', 'One shot')], max_length=10, verbose_name='Type')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('time_step', models.IntegerField(blank=True, null=True, verbose_name='MS from start of day')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date time of intake')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='medications.Prescription', verbose_name='Prescription')),
            ],
            options={
                'verbose_name': 'TimeSlot',
                'verbose_name_plural': 'TimeSlots',
                'db_table': 'time_slots',
            },
        ),
    ]
