# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-15 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0025_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('time-slots', 'Time slots'), ('fixed-times', 'Fixed times'), ('fixed-times-dow', 'Fixed times by day of week'), ('one-shot', 'One shot'), ('conditional', 'Conditional')], default='conditional', max_length=20),
        ),
    ]
