# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-11 15:17
from __future__ import unicode_literals

from django.db import migrations


def create_wish_perm(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    content_type, _ = ContentType.objects.get_or_create(model='user', app_label='accounts')
    Permission.objects.create(name='Can use wish connector', codename='wish_connector', content_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_wish_perm, reverse_code=migrations.RunPython.noop),
    ]
