# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 06:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='interval',
            field=models.IntegerField(default=1, verbose_name='Repeat at intervals'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='periodic',
            field=models.CharField(blank=True, choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=100, null=True, verbose_name='Periodic'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repetitions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(max_length=128), blank=True, default=['12:00:00'], null=True, size=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], null=True, size=None),
        ),
    ]
