# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 12:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181004_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(max_length=128), blank=True, null=True, size=None),
        ),
    ]
