# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20181004_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='periodic',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='times',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='week_days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='root_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.TimeField(null=True, verbose_name='Task Time'),
        ),
    ]
