# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 09:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_schedule_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='task',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
