# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_fill_up_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.BooleanField(default=False, verbose_name='Is time slot'),
        ),
    ]
