# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20181030_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default='12:00', null=True, verbose_name='Task Time'),
        ),
    ]
