# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_schedule_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='creator',
        ),
    ]
