# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wounds', '0012_remove_wound_treatment'),
        ('tasks', '0016_auto_20181211_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='wound',
        ),
        migrations.AddField(
            model_name='schedule',
            name='t_wound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wounds.Wound', verbose_name='Wound'),
        ),
    ]
