# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_auto_20181219_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatedTask',
            fields=[
                ('root_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(default='12:00', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('periodic', models.CharField(blank=True, max_length=5, null=True)),
                ('slot', models.BooleanField(default=False)),
                ('times', models.CharField(blank=True, max_length=255, null=True)),
                ('repeats', models.IntegerField()),
                ('week_days', models.CharField(blank=True, max_length=64, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_repeats', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RepeatedTask',
                'verbose_name_plural': 'RepeatedTasks',
                'db_table': 'repeatedtasks',
                'ordering': ('root_id',),
            },
        ),
    ]
