# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0019_repeatedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatedtask',
            name='max_repeats',
        ),
        migrations.AddField(
            model_name='repeatedtask',
            name='interval',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repeatedtask',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repeatedtask',
            name='repeats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
