# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


def fill_up_category_icons(apps, schema_editor):
    category_model = apps.get_model('tasks', 'Category')
    for category in category_model.objects.all():
        category.icon = f'tasks/icons/{category.slug}.svg'
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tasks', '0021_auto_20190513_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auth.Group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('tasks/icons/accompaniment-appointments-and-procedures.svg', 'Accompaniment, Appointments and Procedures'), ('tasks/icons/assessment-and-protection.svg', 'Assessment and Protection'), ('tasks/icons/basic-nursing-care.svg', 'Basic nursing care'), ('tasks/icons/physio-treatment.svg', 'Physio Treatment'), ('tasks/icons/psychol-care.svg', 'Psycho care'), ('tasks/icons/relational-treatment-and-care.svg', 'Relational treatment and care'), ('tasks/icons/sa-monitoring.svg', 'SA monitoring'), ('tasks/icons/sample.svg', 'Sample'), ('tasks/icons/technical-act.svg', 'Technical act'), ('tasks/icons/therapeutic-activity.svg', 'Therapeutic activity'), ('tasks/icons/therapeutic-education.svg', 'Therapeutic education')], max_length=255, null=True, verbose_name='Static Icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Dynamic Icon'),
        ),
        migrations.RunPython(fill_up_category_icons, reverse_code=migrations.RunPython.noop),
    ]
