# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-22 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import lifeline.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20190517_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=lifeline.storage_backends.PublicStaticStorage(), upload_to='', verbose_name='Dynamic Icon'),
        ),
    ]
