# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-23 07:35
from __future__ import unicode_literals

from django.db import migrations


def add_medication_category(apps, schema_editor):
    category_model = apps.get_model('tasks', 'Category')
    category_model.objects.create(name="Medication", name_en="Medication", icon='tasks/icons/medication.svg')


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20190522_1135'),
    ]

    operations = [
        migrations.RunPython(add_medication_category, reverse_code=migrations.RunPython.noop),
    ]
