# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
