# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20181005_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelTable(
            name='unit',
            table='units',
        ),
    ]
