# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 16:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0013_auto_20181112_1338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('canfor', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Canfor Answers')),
                ('frogs', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Frogs Answers')),
                ('katz', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Katz Answers')),
                ('result', models.IntegerField(verbose_name='User points')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='Patient File')),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'db_table': 'evaluations',
                'ordering': ('-created',),
            },
        ),
    ]
