# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20181127_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='created_by',
            new_name='user',
        ),
    ]
