# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-21 14:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_auto_20181219_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(verbose_name='Answer')),
                ('answer_fr', models.TextField(null=True, verbose_name='Answer')),
                ('answer_nl', models.TextField(null=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answers',
                'ordering': ('answer',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_en', models.TextField(verbose_name='Question')),
                ('question_fr', models.TextField(null=True, verbose_name='Question')),
                ('question_nl', models.TextField(null=True, verbose_name='Question')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('choice_filed', 'Choice Filed'), ('date', 'Date')], default='text', max_length=255, verbose_name='Question Type')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ('survey',),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=255, unique=True, verbose_name='Survey Name')),
                ('survey_name_en', models.CharField(max_length=255, unique=True, verbose_name='Survey Name')),
                ('survey_name_fr', models.CharField(max_length=255, null=True, unique=True, verbose_name='Survey Name')),
                ('survey_name_nl', models.CharField(max_length=255, null=True, unique=True, verbose_name='Survey Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'db_table': 'surveys',
                'ordering': ('survey_name',),
            },
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='type',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Evaluation Name'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='static_results',
            field=models.TextField(blank=True, null=True, verbose_name='Survey static results'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='static_results_en',
            field=models.TextField(blank=True, null=True, verbose_name='Survey static results'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='static_results_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Survey static results'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='static_results_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Survey static results'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='survey_results',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Surveys results'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.Question'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='survey_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='evaluations.Survey', verbose_name='Type'),
        ),
    ]
