# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_disable_edit_in_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Survey Name'),
        ),
    ]
