# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_remove_evaluation_results_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pk', 'survey'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ('name',), 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_groups',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_name_fr',
            new_name='name_fr',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='survey_name_nl',
            new_name='name_nl',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('choice_filed', 'Choice Field'), ('date', 'Date')], default='text', max_length=255, verbose_name='Question Type'),
        ),
    ]
