# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0016_auto_20190531_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id', 'answer'), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id', 'survey'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ('id', 'name'), 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
