# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-14 13:15
from __future__ import unicode_literals

from django.db import migrations


def create_archived_active_perms(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    content_type, _ = ContentType.objects.get_or_create(model='evaluation', app_label='evaluations')
    Permission.objects.create(
        name='Can view active evaluation',
        codename='view_active_evaluation',
        content_type=content_type
    )
    Permission.objects.create(
        name='Can view archive evaluation',
        codename='view_archive_evaluation',
        content_type=content_type
    )


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0017_auto_20190531_1501'),
    ]

    operations = [
        migrations.RunPython(create_archived_active_perms, reverse_code=migrations.RunPython.noop),
    ]
