# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0006_auto_20181009_1421'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalsParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('BP', 'Blood pressure'), ('P', 'Pulse'), ('H', 'Height'), ('T', 'Temperature'), ('BS', 'Blood sugar'), ('W', 'Weight'), ('O', 'O2 saturation'), ('BR', 'Breathing rate')], max_length=3, verbose_name='Type')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.File', verbose_name='Patient File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Vitals Parameter',
                'verbose_name_plural': 'Vitals Parameters',
                'db_table': 'vitals_param',
                'ordering': ('created',),
            },
        ),
    ]
