# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_auto_20181011_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsparam',
            options={'ordering': ('-created',), 'verbose_name': 'Vitals Parameter', 'verbose_name_plural': 'Vitals Parameters'},
        ),
    ]
