# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0003_auto_20181011_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsparam',
            name='type',
            field=models.CharField(choices=[('pressure', 'Blood pressure'), ('pulse', 'Pulse'), ('height', 'Height'), ('temp', 'Temperature'), ('sugar', 'Blood sugar'), ('weight', 'Weight'), ('saturation', 'O2 saturation'), ('breath', 'Breathing rate')], max_length=10, verbose_name='Type'),
        ),
    ]
