from django.utils.translation import ugettext_lazy as _

RELATIONS = (
    ('wife', _('Wife / Husband')),
    ('partner', _('Partner')),
    ('child', _('Child')),
    ('parent', _('Parent')),
    ('grandparent', _('Grandparent')),
    ('brother', _('Brother / Sister')),
    ('other_family', _('Other family member')),
    ('friend', _('Friend')),
    ('roommate', _('Roommate')),
    ('general', _('General practitioner')),
    ('specialist', _('Specialist doctor')),
    ('lawyer', _('Lawyer')),
    ('attorney', _('Attorney for financial power')),
    ('probation', _('Probation officer')),
    ('judge', _('Youth Judge')),
    ('educator', _('Educator')),
    ('other', _('Other relation'))
)

TASKS_FILTER = (
    ('daily', _('Patients with tasks of the day')),
    ('my', _('Patients with tasks assigned to me')),
    ('due', _('Patients with due tasks'))
)

SEX = (
    ('F', _('Female')),
    ('I', _('Indeterminate')),
    ('M', _('Male'))
)

LANGUAGES = (
    ('E', _('English')),
    ('F', _('French')),
    ('G', _('German')),
    ('S', _('Spanish')),
    ('I', _('Italian')),
    ('D', _('Dutch'))
)

DOCUMENT_TYPES = (
    ('B_ID', _('Belgian identity card')),
    ('B_FN', _('Belgian card of foreign resident')),
    ('FN_ID', _('Foreign identity card'))
)

CARD_TYPES = (
    ('CHI', _('Child')),
    ('SPO', _('Spouse')),
    ('B/S', _('Brother/sister')),
    ('PAR', _('Parent'))
)

MARITAL_STATUSES = (
    ('M', _('Married')),
    ('SI', _('Single')),
    ('D', _('Divorced')),
    ('H', _('Co-habitant')),
    ('U', _('Unknown')),
    ('SE', _('Separated')),
    ('W', _('Widowed'))
)

PATIENT_STATUSES = (
    ('E', _('Emergency')),
    ('I', _('Inpatient')),
    ('O', _('Outpatient')),
    ('P', _('Preadmit')),
    ('R', _('Recurring patient')),
    ('B', _('Obstetrics')),
    ('C', _('Commercial Account')),
    ('N', _('Not Applicable')),
    ('U', _('Unknown'))
)

RELIGIONS = (
    ('ADV', _('Adventist')),
    ('AOG', _('Assembly of God')),
    ('BAP', _('Baptist')),
    ('BUD', _('Buddhist')),
    ('CAT', _('Catholic')),
    ('JW', _('Jehovan\'s Witness')),
    ('JSH', _('Jewish')),
    ('LUT', _('Lutheran')),
    ('MRN', _('Mormon')),
    ('NO', _('None')),
    ('ORT', _('Orthodox')),
    ('OTH', _('Other')),
    ('PST', _('Protestant')),
    ('QUA', _('Quaker')),
    ('ISL', _('Islam'))
)

HUB_SHARING = (
    ('Y', _('Yes')),
    ('N', _('No'))
)

DEPENDANTS = (
    ('NO', _('No dependants')),
    ('WITH', _('With dependants'))
)

OCCUPATIONS = (
    ('PH', _('Policyholder')),
    ('PTR', _('Partner')),
    ('PRT', _('Parent')),
    ('CH', _('Child')),
    ('OTH', _('Other beneficiary'))
)

INCOME_ORIGIN = (
    ('WRK', _('Work income')),
    ('ANT', _('Annuitant allowance')),
    ('UNE', _('Unemployment allowance')),
    ('HIA', _('Health insurance allowance')),
    ('HIF', _('Health insurance with Federal allowance')),
    ('FA', _('Federal allowance')),
    ('SOC', _('Social services allowance')),
    ('FAM', _('Family allowance')),
    ('RET', _('Retiring allowance')),
    ('NO', _('No income')),
    ('OTH', _('Other'))
)

ADMISSION = (
    ('ISO', _('Isolated')),
    ('FAM', _('With own family')),
    ('PAR', _('With parents')),
    ('SHR', _('Roomsharing')),
    ('OTH_FAM', _('With other family or substitude')),
    ('RET', _('Retirement home')),
    ('DIS', _('Disabled care facility')),
    ('HM_LESS', _('Homeless shelter')),
    ('COM', _('Community housing')),
    ('JUS', _('Justice facility')),
    ('OTH_COM', _('Other community housing')),
    ('PS_HOSP', _('Psychiatric hospital')),
    ('PS_NURS', _('Psychiatric nursing home')),
    ('SLT', _('Shelter housing')),
    ('PLC', _('Family placement')),
    ('ALT_PS', _('Alternative psychiatric housing')),
    ('GEN', _('General hospital')),
    ('OTH_THE', _('Other therapeutic housing')),
    ('UNS', _('Unspecified')),
    ('UNK', _('Unknown'))
)

EDUCATION = (
    ('NM', _('Normal')),
    ('SP', _('Special')),
    ('NN', _('None')),
    ('UN', _('Unknown'))
)

EDUCATION_PATHWAY = (
    ('PR', _('Primary')),
    ('LHS', _('Lower high school')),
    ('HS', _('High school')),
    ('UN', _('University')),
    ('OTH', _('Other special education')),
    ('UNK', _('Unknown'))
)

COUNTRIES = (
    ('B', _('BELGIUM')),
    ('BD', _('BANGLADESH')),
    ('BDS', _('BARBADOS')),
    ('BER', _('BERMUDA')),
    ('BG', _('BULGARIA')),
    ('BH', _('BELIZE')),
    ('BHU', _('BHUTAN')),
    ('BIH', _('BOSNIA AND HERZEGOVINA')),
    ('BLR', _('BELARUS')),
    ('BOL', _('BOLIVIA')),
    ('BR', _('BRAZIL')),
    ('BRN', _('BAHREIN')),
    ('BRU', _('BRUNEI')),
    ('BS', _('BAHAMAS')),
    ('BUF', _('BURKINA FASO')),
    ('BUR', _('MYANMAR')),
    ('BVI', _('BRITISH VIRGIN ISLANDS')),
    ('C', _('CUBA')),
    ('CAF', _('CENTRAL AFRICAN REPUBLIC')),
    ('CAM', _('CAMEROON')),
    ('CD', _('CONGO (REP. DEMOC. )')),
    ('CDN', _('CANADA')),
    ('CGO', _('CONGO')),
    ('CH', _('SWITZERLAND')),
    ('CI', _('IVORY COAST')),
    ('CL', _('SRI LANKA')),
    ('CO', _('COLOMBIA')),
    ('COK', _('COOK ISLANDS')),
    ('COM', _('COMOROS')),
    ('CPV', _('CAP-VERT')),
    ('CR', _('COSTA RICA')),
    ('CY', _('CYPRUS')),
    ('CYM', _('CAYMAN ISLANDS')),
    ('CZ', _('CZECH REPUBLIC')),
    ('D', _('GERMANY')),
    ('DJI', _('DJIBOUTI')),
    ('DK', _('DENMARK')),
    ('DOM', _('DOMINICA')),
    ('DY', _('BENIN')),
    ('DZ', _('ALGERIA')),
    ('E', _('SPAIN')),
    ('EAK', _('KENYA')),
    ('EAU', _('UNITED ARAB EMIRATES')),
    ('EAZ', _('TANZANIA')),
    ('EC', _('ECUADOR')),
    ('ERI', _('ERITREA')),
    ('EST', _('ESTONIA')),
    ('ET', _('EGYPT')),
    ('ETH', _('ETHIOPIA')),
    ('F', _('FRANCE')),
    ('FI', _('FINLAND')),
    ('FJI', _('FIJI')),
    ('FL', _('LIECHTENSTEIN')),
    ('FLK', _('FALKLAND ISLANDS')),
    ('FR', _('FAROE ISLANDS')),
    ('FSM', _('MICRONESIA')),
    ('G', _('GABON')),
    ('GB', _('UNITED KINGDOM')),
    ('GBZ', _('GIBRALTAR')),
    ('GCA', _('GUATEMALA')),
    ('GDL', _('GUADELOUPE')),
    ('GEO', _('GEORGIA')),
    ('GH', _('GHANA')),
    ('GNB', _('GUINEA-BISSAU')),
    ('GNQ', _('EQUATORIAL GUINEA')),
    ('GR', _('GREECE')),
    ('GRE', _('GRENADA')),
    ('GRL', _('GREENLAND')),
    ('GUA', _('GUAM')),
    ('GUE', _('GUINEA')),
    ('GUF', _('FRENCH GUIANA')),
    ('GUY', _('GUYANA')),
    ('H', _('HUNGARY')),
    ('HK', _('HONG KONG')),
    ('HKJ', _('JORDAN')),
    ('HM', _('HEARD ISLAND AND MCDONALD ISLANDS')),
    ('HUN', _('HONDURAS')),
    ('HRV', _('CROATIA')),
    ('I', _('ITALY')),
    ('IL', _('ISRAEL')),
    ('IND', _('INDIA')),
    ('IR', _('IRAN')),
    ('IRL', _('IRELAND')),
    ('IRQ', _('IRAQ')),
    ('IS', _('ICELAND')),
    ('J', _('JAPAN')),
    ('JA', _('JAMAICA')),
    ('K', _('CAMBODIA')),
    ('KAZ', _('KAZAKHSTAN')),
    ('KGZ', _('KYRGYZSTAN')),
    ('KIR', _('KIRIBATI')),
    ('KNA', _('SAINT KITTS AND NEVIS')),
    ('KRN', _('NORTH KOREA')),
    ('KRS', _('SOUTH KOREA')),
    ('KWT', _('KUWAIT')),
    ('L', _('LUXEMBOURG')),
    ('LAO', _('LAOS')),
    ('LAU', _('UGANDA')),
    ('LB', _('LIBERIA')),
    ('LS', _('LESOTHO')),
    ('LT', _('LITHUANIA')),
    ('LV', _('LATVIA')),
    ('LY', _('LIBYA')),
    ('M', _('MALTA')),
    ('MA', _('MOROCCO')),
    ('MAC', _('MACAU')),
    ('MAL', _('MALAYSIA')),
    ('MC', _('MONACO')),
    ('MDA', _('MOLDAVIA')),
    ('MDR', _('MADAGASCAR')),
    ('MDV', _('MALDIVES')),
    ('ME', _('MONTENEGRO')),
    ('MEX', _('MEXICO')),
    ('MHL', _('MARSHALL ISLANDS')),
    ('MKD', _('MACEDONIA')),
    ('MLI', _('MALI')),
    ('MNP', _('NORTHERN MARIANA ISLANDS')),
    ('MOC', _('MOZAMBIQUE')),
    ('MON', _('MONGOLIA')),
    ('MRT', _('MARTINIQUE')),
    ('MSR', _('MONTSERRAT')),
    ('MUS', _('MAURITIUS')),
    ('MW', _('MALAWI')),
    ('MYT', _('MAYOTTE')),
    ('NAU', _('NAURU')),
    ('NCL', _('NEW CALEDONIA')),
    ('NEP', _('NEPAL')),
    ('NFK', _('NORFOLK ISLAND')),
    ('NIC', _('NICARAGUA')),
    ('NIU', _('NIUE')),
    ('NL', _('NETHERLANDS')),
    ('NOR', _('NORWAY')),
    ('NZ', _('NEW ZEALAND')),
    ('OMN', _('OMAN')),
    ('P', _('PORTUGAL')),
    ('PA', _('PANAMA')),
    ('PAK', _('PAKISTAN')),
    ('PCN', _('PITCAIRN ISLANDS')),
    ('PE', _('PERU')),
    ('PL', _('POLAND')),
    ('PLW', _('PALAU')),
    ('PNG', _('PAPUA NEW GUINEA')),
    ('POR', _('PORTO RICO')),
    ('PS', _('PALESTINE')),
    ('PY', _('PARAGUAY')),
    ('PYF', _('FRENCH POLYNESIA')),
    ('QAT', _('QATAR')),
    ('RA', _('ARGENTINA')),
    ('RB', _('BOTSWANA')),
    ('RC', _('CHINA')),
    ('RCH', _('CHILE')),
    ('REU', _('REUNION')),
    ('RH', _('HAITI')),
    ('RI', _('INDONESIA')),
    ('RIM', _('MAURITANIA')),
    ('RL', _('LEBANON')),
    ('RN', _('NIGER')),
    ('RO', _('ROMANIA')),
    ('RP', _('PHILIPPINES')),
    ('RS', _('SERBIA')),
    ('RSM', _('SAN MARINO')),
    ('RU', _('BURUNDI')),
    ('RUS', _('RUSSIA')),
    ('RWA', _('RWANDA')),
    ('S', _('SWEDEN')),
    ('SAO', _('WESTERN SAHARA')),
    ('SD', _('SWAZILAND')),
    ('SGP', _('SINGAPORE')),
    ('SHN', _('SAINT HELENA')),
    ('SJM', _('SVALBARD AND JAN MAYEN')),
    ('SK', _('SLOVAKIA')),
    ('SLB', _('SOLOMON ISLANDS')),
    ('SLO', _('SLOVENIE')),
    ('SLV', _('SALVADOR')),
    ('SME', _('SURINAME')),
    ('SN', _('SENEGAL')),
    ('SOD', _('SUDAN')),
    ('SP', _('SOMALIE')),
    ('SPM', _('SAINT PIERRE AND MIQUELON')),
    ('SSD', _('SOUTH SUDAN')),
    ('STP', _('SAO TOME AND PRINCIPE')),
    ('SWA', _('NAMIBIA')),
    ('SY', _('SEYCHELLES')),
    ('SYR', _('SYRIA')),
    ('T', _('THAILAND')),
    ('TCA', _('TURKS AND CAICOS ISLANDS')),
    ('TCH', _('CHAD')),
    ('TG', _('TOGO')),
    ('TJK', _('TAJIKISTAN')),
    ('TKL', _('TOKELAU')),
    ('TKM', _('TURKMENISTAN')),
    ('TMP', _('WEST TIMOR')),
    ('TN', _('TUNISIA')),
    ('TOG', _('TONGA')),
    ('TR', _('TURKEY')),
    ('TT', _('TRINIDAD AND TOBAGO')),
    ('TUV', _('TUVALU')),
    ('TW', _('TAIWAN')),
    ('U', _('URUGUAY')),
    ('UKR', _('UKRAINE')),
    ('USA', _('UNITED STATES OF AMERICA')),
    ('UZB', _('UZBEKISTAN')),
    ('V', _('VATICAN')),
    ('VAU', _('VANUATU')),
    ('VCT', _('SAINT VINCENT AND THE GRENADINES')),
    ('VIR', _('UNITED STATES VIRGIN ISLANDS')),
    ('VN', _('VIETNAM')),
    ('VZA', _('VENEZUELA')),
    ('WAG', _('GAMBIA')),
    ('WAL', _('SIERRA LEONE')),
    ('WAN', _('NIGERIA')),
    ('WD', _('DOMINICAN REPUBLIC')),
    ('WL', _('SAINT LUCIA')),
    ('WLF', _('WALLIS AND FUTUNA')),
    ('WSM', _('SAMOA')),
    ('YMM', _('YEMEN')),
    ('Z', _('ZAMBIA')),
    ('ZAF', _('SOUTH AFRICA')),
    ('ZIM', _('ZIMBABWE'))
)

HEALTH_INSURANCE = (
    ('100', 'Alliance nationale des mutualits chértiennes'),
    ('311', 'Bond moyson Oost-Vlaanderen'),
    ('309', 'Bond moyson West-Vlaanderen'),
    ('602', 'Bruxelles-Capitale'),
    ('600', 'Caisse auxiliaire d\'assurance maladie-invalidité'),
    ('900', 'Caisse des Soins de santé de HR Rail '),
    ('910', 'Caisse des Soins de santé de HR Rail - CMR Bruxelles'),
    ('950', 'Caisse des Soins de santé de HR Rail - CMR Mons'),
    ('951', 'Caisse des Soins de santé de HR Rail - CMR Mons'),
    ('940', 'Caisse des Soins de santé de HR Rail - CMR Namur'),
    ('941', 'Caisse des Soins de santé de HR Rail - CMR Namur'),
    ('942', 'Caisse des Soins de santé de HR Rail - CMR Namur'),
    ('108', 'Christelijk ziekenfonds - Sint-Pietersbond'),
    ('126', 'Christelijk ziekenfonds Sint-Michielsbond'),
    ('110', 'Christelijke mutualiteit'),
    ('131', 'Christelijke mutualiteit Limburg'),
    ('120', 'Christelijke mutualiteit Middden- Vlaanderen'),
    ('112', 'Christelijke mutualiteit Oostende - Veurne é Diksmuide'),
    ('105', 'Christelijke mutualiteit regio Mechelen - Turnhout'),
    ('113', 'Christelijke mutualiteit Roeselare - Tielt'),
    ('101', 'Christelijke mutualiteit van het arrondissement Antwerpen'),
    ('121', 'Christelijke mutualiteit van het land van Waas en Dendermonde'),
    ('111', 'Christelijke mutualiteit Zuid-West-Vlaanderen'),
    ('304', 'De Voorzorg - Socialistische mutualiteit van de provincie Antwerpen'),
    ('322', 'De Voorzorg é Mutualiteitsverbond van Limburg'),
    ('306', 'Fédération des mutualités socialistes du Brabant'),
    ('515', 'Freie Krankenkasse'),
    ('601', 'Gewestelijke dienst Antwerpen'),
    ('607', 'Gewestelijke dienst Limburg'),
    ('604', 'Gewestelijke dienst Oost-Vlaanderen'),
    ('603', 'Gewestelijke dienst West-Vlaanderen'),
    ('930', 'Kas der geneeskundige verzorging van HR Rail é GGC Brugge'),
    ('931', 'Kas der geneeskundige verzorging van HR Rail é GGC Brugge'),
    ('920', 'Kas der geneeskundige verzorging van HR Rail é GGC Hasselt'),
    ('921', 'Kas der geneeskundige verzorging van HR Rail é GGC Hasselt'),
    ('922', 'Kas der geneeskundige verzorging van HR Rail é GGC Hasselt'),
    ('415', 'Liberale mutualiteit Limburg'),
    ('417', 'Liberale Mutualiteit Plus'),
    ('407', 'Liberale Mutualiteit van Oost-Vlaanderen'),
    ('403', 'ML MUTPLUS.be'),
    ('228', 'Mutualia - Mutualité neutre'),
    ('132', 'Mutualité chrétienne de la Province de Luxembourg'),
    ('134', 'Mutualité chrétienne de la Province de Namur'),
    ('130', 'Mutualité chrétienne de Liége'),
    ('137', 'Mutualité Chrétienne de Verviers - Eupen'),
    ('109', 'Mutualité chrétienne du Brabant wallon'),
    ('128', 'Mutualité chrétienne du Hainaut Oriental'),
    ('129', 'Mutualité chrétienne Hainaut-Picardie'),
    ('418', 'Mutualité Libérale du Luxembourg'),
    ('409', 'Mutualité Libérale Hainaut-Namur'),
    ('414', 'Mutualité Libérale Liége'),
    ('216', 'Mutualité neutre'),
    ('135', 'Mutualité Saint-Michel'),
    ('323', 'Mutualité socialiste du Luxembourg'),
    ('315', 'Mutualité Solidaris Mons-Wallonie Picarde'),
    ('235', 'Neutraal ziekenfonds Vlaanderen'),
    ('622', 'Office régional - Brabant wallon'),
    ('615', 'Office régional - Section de Charleroi'),
    ('620', 'Office régional é Section de Malmedy'),
    ('610', 'Office régional d\'Eupen'),
    ('606', 'Office régional de Liége'),
    ('609', 'Office régional de Namur'),
    ('605', 'Office régional du Hainaut'),
    ('608', 'Office régional du Luxembourg'),
    ('506', 'Omnimut mutualité libre de Wallonie'),
    ('501', 'OZ Onafhankelijk Ziekenfonds'),
    ('509', 'Partena - Mutualité libre'),
    ('526', 'PARTENA - Onafhankelijk ziekenfonds'),
    ('527', 'PARTENA é Mutualité Libre'),
    ('319', 'Solidaris - Mutualité socialiste et syndicale de la Province de Liége'),
    ('305', 'Solidaris mutualité Brabant wallon'),
    ('325', 'Solidaris mutualité Province de Namur'),
    ('317', 'Solidaris Mutualité socialiste du Centre, Charleroi et Soignies'),
    ('206', 'Symbio'),
    ('400', 'Union nationale des Mutualités Libérales'),
    ('500', 'Union nationale des mutualités libres'),
    ('200', 'Union nationale des mutualités neutres'),
    ('300', 'Union nationale des mutualités socialistes'),
    ('203', 'Vlaams & Neutraal Ziekenfonds'),
    ('612', 'Vlaams Brabant')
)

HEADING_HEALTH_INSURANCE = (
    ('1', _('Ordinary policyholder (75%)')),
    ('2', _('WDRO')),
    ('3', _('Self-employed (high risk)')),
    ('4', _('Self-employed (low risk)')),
    ('7', _('SPPIS: OA part + patient part')),
    ('8', _('Payable by health insurance policy')),
)
