# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category slug'),
        ),
    ]
