# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20181114_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='created_by',
            new_name='user',
        ),
    ]
